/* eslint-disable prettier/prettier */
import { ServerOptions } from './types/ServerOptions';

export default {
  secretKey: 'THISISMYSECURETOKEN',
  host: 'http://localhost',
  port: '21465',
  deviceName: 'WppConnect',
  poweredBy: 'WPPConnect-Server',
  startAllSession: true,
  tokenStoreType: 'file',
  maxListeners: 15,
  customUserDataDir: './userDataDir/',
  webhook: {
    url: null,
    autoDownload: true,
    uploadS3: false,
    readMessage: true,
    allUnreadOnStart: false,
    listenAcks: true,
    onPresenceChanged: true,
    onParticipantsChanged: true,
    onReactionMessage: true,
    onPollResponse: true,
    onRevokedMessage: true,
    onLabelUpdated: true,
    onSelfMessage: false,
    ignore: ['status@broadcast'],
  },
  websocket: {
    autoDownload: false,
    uploadS3: false,
  },
  chatwoot: {
    sendQrCode: true,
    sendStatus: true,
  },
  archive: {
    enable: false,
    waitTime: 10,
    daysToArchive: 45,
  },
  log: {
    level: 'silly', // Before open a issue, change level to silly and retry a action
    logger: ['console', 'file'],
  },
  createOptions: {
    browserArgs: [
      '--disable-web-security',
      '--no-sandbox',
      '--disable-setuid-sandbox',
      '--disable-web-security',
      '--aggressive-cache-discard',
      '--disable-cache',
      '--disable-application-cache',
      '--disable-offline-load-stale-cache',
      '--disk-cache-size=0',
      '--disable-background-networking',
      '--disable-background-timer-throttling',
      '--disable-backgrounding-occluded-windows',
      '--disable-renderer-backgrounding',
      '--disable-default-apps',
      '--disable-extensions',
      '--disable-sync',
      '--disable-dev-shm-usage',
      '--disable-gpu',
      '--disable-software-rasterizer',
      '--disable-translate',
      '--disable-features=VizDisplayCompositor',
      '--disable-features=IsolateOrigins,site-per-process',
      '--disable-blink-features=AutomationControlled',
      '--hide-scrollbars',
      '--metrics-recording-only',
      '--mute-audio',
      '--no-first-run',
      '--no-zygote',
      '--single-process',
      '--safebrowsing-disable-auto-update',
      '--ignore-certificate-errors',
      '--ignore-ssl-errors',
      '--ignore-certificate-errors-spki-list',
      '--disable-breakpad',
      '--disable-component-update',
      '--disable-print-preview',
      '--disable-prompt-on-repost',
      '--disable-hang-monitor',
      '--disable-ipc-flooding-protection',
      '--disable-client-side-phishing-detection',
      '--enable-simple-cache-backend',
      '--enable-tcp-fast-open',
      '--disable-webgl',
      '--disable-threaded-scrolling',
      '--disable-smooth-scrolling',
      '--disable-composited-antialiasing',
      '--disable-canvas-aa',
      '--disable-2d-canvas-clip-aa',
      '--disable-gl-drawing-for-tests',
      '--force-color-profile=srgb',
      // Args específicos para estabilidad DOM y fix de ProtocolError
      '--disable-background-timer-throttling',
      '--disable-renderer-backgrounding',
      '--disable-backgrounding-occluded-windows',
      '--disable-ipc-flooding-protection',
      '--enable-features=NetworkService,NetworkServiceLogging',
      '--disable-features=TranslateUI',
      '--disable-features=Translate',
      '--disable-component-extensions-with-background-pages',
      '--disable-features=VizDisplayCompositor',
      '--disable-features=IsolateOrigins',
      '--disable-site-isolation-trials',
      '--disable-features=BlockInsecurePrivateNetworkRequests',
      '--disable-features=OutOfBlinkCors',
      '--disable-blink-features=AutomationControlled',
      '--disable-dev-shm-usage',
      '--disable-accelerated-2d-canvas',
      '--no-zygote',
      '--single-process',
      '--disable-gpu',
    ],
    /**
     * Example of configuring the linkPreview generator
     * If you set this to 'null', it will use global servers; however, you have the option to define your own server
     * Clone the repository https://github.com/wppconnect-team/wa-js-api-server and host it on your server with ssl
     *
     * Configure the attribute as follows:
     * linkPreviewApiServers: [ 'https://www.yourserver.com/wa-js-api-server' ]
     */
    linkPreviewApiServers: null,
    puppeteerOptions: {
      args: [
        '--no-sandbox',
        '--disable-setuid-sandbox',
        '--disable-dev-shm-usage',
        '--disable-blink-features=AutomationControlled',
        '--user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36',
        '--window-size=1366,768',
        '--disable-web-security',
        '--disable-features=IsolateOrigins,site-per-process',
        '--disable-background-timer-throttling',
        '--disable-renderer-backgrounding',
        '--disable-backgrounding-occluded-windows',
        '--disable-ipc-flooding-protection',
        '--disable-default-apps',
        '--disable-sync',
        '--disable-translate',
        '--disable-extensions',
        '--disable-component-extensions-with-background-pages',
        '--disable-background-networking',
        '--disable-client-side-phishing-detection',
        '--disable-component-update',
        '--force-webrtc-ip-handling-policy=default_public_interface_only',
        '--disable-webgl',
        '--disable-features=WebRtcHideLocalIpsWithMdns',
        '--disable-features=WebRtcLocalIpsAllowedUrls',
        '--disable-features=PrivacySandboxSettings4',
        '--disable-features=InterestCohortFeaturePolicy',
        '--enable-features=NetworkService,NetworkServiceLogging',
        '--disable-features=VizDisplayCompositor',
        '--disable-features=OutOfBlinkCors'
      ],
      headless: true,
      devtools: false,
      executablePath: '/usr/bin/google-chrome-stable',
      timeout: 0,
      protocolTimeout: 0,
      slowMo: 100,
      waitForInitialPage: true,
      defaultViewport: {
        width: 1366,
        height: 768,
        deviceScaleFactor: 1,
        isMobile: false,
        hasTouch: false,
        isLandscape: false
      },
    multiDevice: true,
    authTimeoutMs: 90000,
    takeoverOnConflict: true,
    takeoverTimeoutMs: 60000,
    cacheEnabled: false,
    disableWelcome: true,
    updatesLog: false,
    logLevel: 'error',
    deviceName: 'Chrome Desktop',
    poweredBy: 'WPPConnect',
    autoClose: 0,
    skipSavePostman: true,
    skipBrokenMethodsCheck: true,
    device: {
      manufacturer: 'Google',
      model: 'Chrome',
      platform: 'Windows',
      os_version: '10',
      wa_version: '2.23.10.78',
    },
    waitForLogin: true,
    waitForLoginTimeoutMs: 60000,
    // Configuración de estabilidad DOM para fix de ProtocolError
    domStability: {
      waitForSelector: 'div[data-testid="side"]',
      waitForTimeout: 45000,
      waitUntil: 'networkidle2',
      checkInterval: 200,
      domContentLoaded: true,
      networkIdleTimeout: 5000
    },
    // Configuración de retry para inyección wapi.js
    wapiInjection: {
      maxRetries: 5,
      retryDelay: 3000,
      waitForReady: true,
      checkInterval: 500
    },
    // Tiempo de espera extendido para carga completa
    loadingTimeout: 60000,
    authTimeoutMs: 120000,
  },
  mapper: {
    enable: false,
    prefix: 'tagone-',
  },
  db: {
    mongodbDatabase: 'tokens',
    mongodbCollection: '',
    mongodbUser: '',
    mongodbPassword: '',
    mongodbHost: '',
    mongoIsRemote: true,
    mongoURLRemote: '',
    mongodbPort: 27017,
    redisHost: 'localhost',
    redisPort: 6379,
    redisPassword: '',
    redisDb: 0,
    redisPrefix: 'docker',
  },
  aws_s3: {
    region: 'sa-east-1' as any,
    access_key_id: null,
    secret_key: null,
    defaultBucketName: null,
    endpoint: null,
    forcePathStyle: null,
  },
} as unknown as ServerOptions;
